[package]
name = "gtfs-realtime-bindings-transit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbjson = "0.3.0"
pbjson-types = "0.3.0"
prost = "0.10.3"
serde = "1.0.137"
serde_json = { version = "1.0.81", features = ["preserve_order"] }

[build-dependencies]
pbjson-build = "0.3.0"
prost-build = "0.10.3"

[dev-dependencies]
assert-json-diff = "2.0.1"
