[package]
name = "gtfs-realtime-bindings-transit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "=3.0.0-alpha.6"
serde_json = { version = "1.0.79", features = ["preserve_order"] }

[build-dependencies]
protobuf-codegen = "=3.0.0-alpha.6"

[dev-dependencies]
assert-json-diff = "2.0.1"

[profile.test]
opt-level = 3
